<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEBRgf6P\restTestKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEBRgf6P/restTestKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEBRgf6P.legacy');

    return;
}

if (!\class_exists(restTestKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEBRgf6P\restTestKernelDevDebugContainer::class, restTestKernelDevDebugContainer::class, false);
}

return new \ContainerEBRgf6P\restTestKernelDevDebugContainer([
    'container.build_hash' => 'EBRgf6P',
    'container.build_id' => '759adaa5',
    'container.build_time' => 1577088492,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEBRgf6P');
